controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

adapters:
    type: attribute
    resource:
        path: ../src/Adapter/In/Http
        namespace: App\Adapter\In\Http

articleMgmtControllers:
    resource:
        path: ../src/ArticleMgmt/Presentation
        namespace: App\ArticleMgmt\Presentation
    type: attribute

Login:
    path: /api/users/login
